export interface ChinaWeatherLocation {
  id: string;
  nameZh: string;
  nameEn: string;
  province: string;
  latitude: number;
  longitude: number;
  priority: number;
}

export const CHINA_WEATHER_LOCATIONS: ChinaWeatherLocation[] = [
  { id: 'beijing', nameZh: '北京', nameEn: 'beijing', province: '北京', latitude: 39.9, longitude: 116.41, priority: 100 },
  { id: 'shanghai', nameZh: '上海', nameEn: 'shanghai', province: '上海', latitude: 31.23, longitude: 121.47, priority: 100 },
  { id: 'tianjin', nameZh: '天津', nameEn: 'tianjin', province: '天津', latitude: 39.13, longitude: 117.2, priority: 95 },
  { id: 'chongqing', nameZh: '重庆', nameEn: 'chongqing', province: '重庆', latitude: 29.56, longitude: 106.55, priority: 95 },
  { id: 'haerbin', nameZh: '哈尔滨', nameEn: 'haerbin', province: '黑龙江', latitude: 45.8, longitude: 126.53, priority: 95 },
  { id: 'changchun', nameZh: '长春', nameEn: 'changchun', province: '吉林', latitude: 43.82, longitude: 125.32, priority: 90 },
  { id: 'shenyang', nameZh: '沈阳', nameEn: 'shenyang', province: '辽宁', latitude: 41.8, longitude: 123.43, priority: 90 },
  { id: 'huhehaote', nameZh: '呼和浩特', nameEn: 'huhehaote', province: '内蒙古', latitude: 40.82, longitude: 111.75, priority: 90 },
  { id: 'taiyuan', nameZh: '太原', nameEn: 'taiyuan', province: '山西', latitude: 37.87, longitude: 112.55, priority: 85 },
  { id: 'shijiazhuang', nameZh: '石家庄', nameEn: 'shijiazhuang', province: '河北', latitude: 38.04, longitude: 114.51, priority: 85 },
  { id: 'jinan', nameZh: '济南', nameEn: 'jinan', province: '山东', latitude: 36.65, longitude: 117.12, priority: 85 },
  { id: 'qingdao', nameZh: '青岛', nameEn: 'qingdao', province: '山东', latitude: 36.07, longitude: 120.38, priority: 80 },
  { id: 'zhengzhou', nameZh: '郑州', nameEn: 'zhengzhou', province: '河南', latitude: 34.75, longitude: 113.62, priority: 85 },
  { id: 'xian', nameZh: '西安', nameEn: 'xian', province: '陕西', latitude: 34.34, longitude: 108.94, priority: 90 },
  { id: 'lanzhou', nameZh: '兰州', nameEn: 'lanzhou', province: '甘肃', latitude: 36.06, longitude: 103.83, priority: 85 },
  { id: 'xining', nameZh: '西宁', nameEn: 'xining', province: '青海', latitude: 36.62, longitude: 101.78, priority: 85 },
  { id: 'yinchuan', nameZh: '银川', nameEn: 'yinchuan', province: '宁夏', latitude: 38.47, longitude: 106.23, priority: 80 },
  { id: 'wulumuqi', nameZh: '乌鲁木齐', nameEn: 'urumqi', province: '新疆', latitude: 43.82, longitude: 87.62, priority: 90 },
  { id: 'lasa', nameZh: '拉萨', nameEn: 'lasa', province: '西藏', latitude: 29.65, longitude: 91.13, priority: 85 },
  { id: 'chengdu', nameZh: '成都', nameEn: 'chengdu', province: '四川', latitude: 30.67, longitude: 104.06, priority: 90 },
  { id: 'kunming', nameZh: '昆明', nameEn: 'kunming', province: '云南', latitude: 25.04, longitude: 102.71, priority: 85 },
  { id: 'guiyang', nameZh: '贵阳', nameEn: 'guiyang', province: '贵州', latitude: 26.65, longitude: 106.63, priority: 85 },
  { id: 'nanning', nameZh: '南宁', nameEn: 'nanning', province: '广西', latitude: 22.82, longitude: 108.37, priority: 85 },
  { id: 'haikou', nameZh: '海口', nameEn: 'haikou', province: '海南', latitude: 20.04, longitude: 110.2, priority: 80 },
  { id: 'guangzhou', nameZh: '广州', nameEn: 'guangzhou', province: '广东', latitude: 23.13, longitude: 113.26, priority: 90 },
  { id: 'shenzhen', nameZh: '深圳', nameEn: 'shenzhen', province: '广东', latitude: 22.54, longitude: 114.06, priority: 90 },
  { id: 'fuzhou', nameZh: '福州', nameEn: 'fuzhou', province: '福建', latitude: 26.08, longitude: 119.3, priority: 85 },
  { id: 'xiamen', nameZh: '厦门', nameEn: 'xiamen', province: '福建', latitude: 24.48, longitude: 118.09, priority: 80 },
  { id: 'nanchang', nameZh: '南昌', nameEn: 'nanchang', province: '江西', latitude: 28.68, longitude: 115.86, priority: 85 },
  { id: 'changsha', nameZh: '长沙', nameEn: 'changsha', province: '湖南', latitude: 28.23, longitude: 112.94, priority: 85 },
  { id: 'wuhan', nameZh: '武汉', nameEn: 'wuhan', province: '湖北', latitude: 30.59, longitude: 114.3, priority: 90 },
  { id: 'hefei', nameZh: '合肥', nameEn: 'hefei', province: '安徽', latitude: 31.82, longitude: 117.23, priority: 85 },
  { id: 'nanjing', nameZh: '南京', nameEn: 'nanjing', province: '江苏', latitude: 32.06, longitude: 118.78, priority: 90 },
  { id: 'suzhou', nameZh: '苏州', nameEn: 'suzhou', province: '江苏', latitude: 31.3, longitude: 120.59, priority: 80 },
  { id: 'hangzhou', nameZh: '杭州', nameEn: 'hangzhou', province: '浙江', latitude: 30.27, longitude: 120.15, priority: 90 },
  { id: 'ningbo', nameZh: '宁波', nameEn: 'ningbo', province: '浙江', latitude: 29.87, longitude: 121.55, priority: 80 },
  { id: 'dalian', nameZh: '大连', nameEn: 'dalian', province: '辽宁', latitude: 38.91, longitude: 121.61, priority: 80 },
  { id: 'qinhuangdao', nameZh: '秦皇岛', nameEn: 'qinhuangdao', province: '河北', latitude: 39.94, longitude: 119.6, priority: 72 },
  { id: 'datong', nameZh: '大同', nameEn: 'datong', province: '山西', latitude: 40.08, longitude: 113.3, priority: 72 },
  { id: 'baotou', nameZh: '包头', nameEn: 'baotou', province: '内蒙古', latitude: 40.66, longitude: 109.84, priority: 72 },
  { id: 'tongliao', nameZh: '通辽', nameEn: 'tongliao', province: '内蒙古', latitude: 43.62, longitude: 122.26, priority: 70 },
  { id: 'qiqihaer', nameZh: '齐齐哈尔', nameEn: 'qiqihaer', province: '黑龙江', latitude: 47.35, longitude: 123.92, priority: 75 },
  { id: 'mudanjiang', nameZh: '牡丹江', nameEn: 'mudanjiang', province: '黑龙江', latitude: 44.58, longitude: 129.6, priority: 72 },
  { id: 'yanji', nameZh: '延吉', nameEn: 'yanji', province: '吉林', latitude: 42.89, longitude: 129.51, priority: 70 },
  { id: 'yantai', nameZh: '烟台', nameEn: 'yantai', province: '山东', latitude: 37.46, longitude: 121.45, priority: 72 },
  { id: 'weihai', nameZh: '威海', nameEn: 'weihai', province: '山东', latitude: 37.51, longitude: 122.12, priority: 72 },
  { id: 'luoyang', nameZh: '洛阳', nameEn: 'luoyang', province: '河南', latitude: 34.62, longitude: 112.45, priority: 72 },
  { id: 'xiangyang', nameZh: '襄阳', nameEn: 'xiangyang', province: '湖北', latitude: 32.01, longitude: 112.12, priority: 70 },
  { id: 'yueyang', nameZh: '岳阳', nameEn: 'yueyang', province: '湖南', latitude: 29.36, longitude: 113.13, priority: 68 },
  { id: 'huangshan', nameZh: '黄山', nameEn: 'huangshan', province: '安徽', latitude: 29.71, longitude: 118.34, priority: 72 },
  { id: 'wenzhou', nameZh: '温州', nameEn: 'wenzhou', province: '浙江', latitude: 27.99, longitude: 120.7, priority: 72 },
  { id: 'jinhua', nameZh: '金华', nameEn: 'jinhua', province: '浙江', latitude: 29.08, longitude: 119.65, priority: 68 },
  { id: 'quanzhou', nameZh: '泉州', nameEn: 'quanzhou', province: '福建', latitude: 24.87, longitude: 118.68, priority: 70 },
  { id: 'ganzhou', nameZh: '赣州', nameEn: 'ganzhou', province: '江西', latitude: 25.83, longitude: 114.93, priority: 68 },
  { id: 'guilin', nameZh: '桂林', nameEn: 'guilin', province: '广西', latitude: 25.27, longitude: 110.29, priority: 75 },
  { id: 'sanya', nameZh: '三亚', nameEn: 'sanya', province: '海南', latitude: 18.25, longitude: 109.51, priority: 72 },
  { id: 'zhuhai', nameZh: '珠海', nameEn: 'zhuhai', province: '广东', latitude: 22.27, longitude: 113.57, priority: 72 },
  { id: 'foshan', nameZh: '佛山', nameEn: 'foshan', province: '广东', latitude: 23.02, longitude: 113.12, priority: 68 },
  { id: 'mianyang', nameZh: '绵阳', nameEn: 'mianyang', province: '四川', latitude: 31.47, longitude: 104.68, priority: 72 },
  { id: 'kangding', nameZh: '康定', nameEn: 'kangding', province: '四川', latitude: 30.05, longitude: 101.96, priority: 72 },
  { id: 'dali', nameZh: '大理', nameEn: 'dali', province: '云南', latitude: 25.61, longitude: 100.27, priority: 70 },
  { id: 'lijiang', nameZh: '丽江', nameEn: 'lijiang', province: '云南', latitude: 26.86, longitude: 100.23, priority: 72 },
  { id: 'zunyi', nameZh: '遵义', nameEn: 'zunyi', province: '贵州', latitude: 27.73, longitude: 106.93, priority: 68 },
  { id: 'rikaze', nameZh: '日喀则', nameEn: 'rikaze', province: '西藏', latitude: 29.27, longitude: 88.88, priority: 70 },
  { id: 'linzhi', nameZh: '林芝', nameEn: 'linzhi', province: '西藏', latitude: 29.65, longitude: 94.36, priority: 70 },
  { id: 'jiayuguan', nameZh: '嘉峪关', nameEn: 'jiayuguan', province: '甘肃', latitude: 39.77, longitude: 98.29, priority: 68 },
  { id: 'zhangye', nameZh: '张掖', nameEn: 'zhangye', province: '甘肃', latitude: 38.93, longitude: 100.45, priority: 68 },
  { id: 'yushu', nameZh: '玉树', nameEn: 'yushu', province: '青海', latitude: 32.99, longitude: 97.01, priority: 70 },
  { id: 'golmud', nameZh: '格尔木', nameEn: 'golmud', province: '青海', latitude: 36.41, longitude: 94.9, priority: 70 },
  { id: 'kashi', nameZh: '喀什', nameEn: 'kashi', province: '新疆', latitude: 39.47, longitude: 75.99, priority: 72 },
  { id: 'yining', nameZh: '伊宁', nameEn: 'yining', province: '新疆', latitude: 43.91, longitude: 81.32, priority: 72 },
  { id: 'aletai', nameZh: '阿勒泰', nameEn: 'aletai', province: '新疆', latitude: 47.85, longitude: 88.14, priority: 72 },
  { id: 'tangshan', nameZh: '唐山', nameEn: 'tangshan', province: '河北', latitude: 39.63, longitude: 118.18, priority: 75 },
  { id: 'baoding', nameZh: '保定', nameEn: 'baoding', province: '河北', latitude: 38.87, longitude: 115.48, priority: 75 },
  { id: 'handan', nameZh: '邯郸', nameEn: 'handan', province: '河北', latitude: 36.62, longitude: 114.48, priority: 72 },
  { id: 'langfang', nameZh: '廊坊', nameEn: 'langfang', province: '河北', latitude: 39.53, longitude: 116.69, priority: 72 },
  { id: 'yuncheng', nameZh: '运城', nameEn: 'yuncheng', province: '山西', latitude: 35.03, longitude: 110.98, priority: 72 },
  { id: 'jinzhong', nameZh: '晋中', nameEn: 'jinzhong', province: '山西', latitude: 37.71, longitude: 112.55, priority: 70 },
  { id: 'chifeng', nameZh: '赤峰', nameEn: 'chifeng', province: '内蒙古', latitude: 42.28, longitude: 118.94, priority: 75 },
  { id: 'ordos', nameZh: '鄂尔多斯', nameEn: 'ordos', province: '内蒙古', latitude: 39.61, longitude: 109.78, priority: 75 },
  { id: 'jinzhou', nameZh: '锦州', nameEn: 'jinzhou', province: '辽宁', latitude: 41.12, longitude: 121.15, priority: 72 },
  { id: 'yingkou', nameZh: '营口', nameEn: 'yingkou', province: '辽宁', latitude: 40.67, longitude: 122.21, priority: 70 },
  { id: 'jilin', nameZh: '吉林', nameEn: 'jilin', province: '吉林', latitude: 43.84, longitude: 126.56, priority: 75 },
  { id: 'siping', nameZh: '四平', nameEn: 'siping', province: '吉林', latitude: 43.16, longitude: 124.36, priority: 70 },
  { id: 'daqing', nameZh: '大庆', nameEn: 'daqing', province: '黑龙江', latitude: 46.58, longitude: 125.03, priority: 75 },
  { id: 'jixi', nameZh: '鸡西', nameEn: 'jixi', province: '黑龙江', latitude: 45.3, longitude: 130.97, priority: 70 },
  { id: 'wuxi', nameZh: '无锡', nameEn: 'wuxi', province: '江苏', latitude: 31.55, longitude: 120.3, priority: 75 },
  { id: 'xuzhou', nameZh: '徐州', nameEn: 'xuzhou', province: '江苏', latitude: 34.26, longitude: 117.18, priority: 75 },
  { id: 'changzhou', nameZh: '常州', nameEn: 'changzhou', province: '江苏', latitude: 31.81, longitude: 119.98, priority: 72 },
  { id: 'shaoxing', nameZh: '绍兴', nameEn: 'shaoxing', province: '浙江', latitude: 30.01, longitude: 120.58, priority: 75 },
  { id: 'taizhou', nameZh: '台州', nameEn: 'taizhou', province: '浙江', latitude: 28.66, longitude: 121.43, priority: 72 },
  { id: 'wuhu', nameZh: '芜湖', nameEn: 'wuhu', province: '安徽', latitude: 31.35, longitude: 118.43, priority: 75 },
  { id: 'bengbu', nameZh: '蚌埠', nameEn: 'bengbu', province: '安徽', latitude: 32.93, longitude: 117.37, priority: 70 },
  { id: 'jiujiang', nameZh: '九江', nameEn: 'jiujiang', province: '江西', latitude: 29.71, longitude: 115.98, priority: 75 },
  { id: 'jingdezhen', nameZh: '景德镇', nameEn: 'jingdezhen', province: '江西', latitude: 29.28, longitude: 117.22, priority: 70 },
  { id: 'weifang', nameZh: '潍坊', nameEn: 'weifang', province: '山东', latitude: 36.77, longitude: 119.1, priority: 75 },
  { id: 'linyi', nameZh: '临沂', nameEn: 'linyi', province: '山东', latitude: 35.06, longitude: 118.34, priority: 75 },
  { id: 'dongying', nameZh: '东营', nameEn: 'dongying', province: '山东', latitude: 37.45, longitude: 118.49, priority: 72 },
  { id: 'kaifeng', nameZh: '开封', nameEn: 'kaifeng', province: '河南', latitude: 34.78, longitude: 114.32, priority: 75 },
  { id: 'nanyang', nameZh: '南阳', nameEn: 'nanyang', province: '河南', latitude: 33.0, longitude: 112.53, priority: 75 },
  { id: 'yichang', nameZh: '宜昌', nameEn: 'yichang', province: '湖北', latitude: 30.7, longitude: 111.28, priority: 75 },
  { id: 'jingzhou', nameZh: '荆州', nameEn: 'jingzhou', province: '湖北', latitude: 30.34, longitude: 112.24, priority: 72 },
  { id: 'zhuzhou', nameZh: '株洲', nameEn: 'zhuzhou', province: '湖南', latitude: 27.84, longitude: 113.15, priority: 75 },
  { id: 'xiangtan', nameZh: '湘潭', nameEn: 'xiangtan', province: '湖南', latitude: 27.84, longitude: 112.94, priority: 72 },
  { id: 'shantou', nameZh: '汕头', nameEn: 'shantou', province: '广东', latitude: 23.35, longitude: 116.67, priority: 75 },
  { id: 'huizhou', nameZh: '惠州', nameEn: 'huizhou', province: '广东', latitude: 23.08, longitude: 114.42, priority: 75 },
  { id: 'liuzhou', nameZh: '柳州', nameEn: 'liuzhou', province: '广西', latitude: 24.32, longitude: 109.42, priority: 75 },
  { id: 'wuzhou', nameZh: '梧州', nameEn: 'wuzhou', province: '广西', latitude: 23.48, longitude: 111.33, priority: 70 },
  { id: 'panzhihua', nameZh: '攀枝花', nameEn: 'panzhihua', province: '四川', latitude: 26.59, longitude: 101.72, priority: 72 },
  { id: 'nanchong', nameZh: '南充', nameEn: 'nanchong', province: '四川', latitude: 30.84, longitude: 106.08, priority: 72 },
  { id: 'qujing', nameZh: '曲靖', nameEn: 'qujing', province: '云南', latitude: 25.49, longitude: 103.79, priority: 75 },
  { id: 'yuxi', nameZh: '玉溪', nameEn: 'yuxi', province: '云南', latitude: 24.36, longitude: 102.55, priority: 72 },
  { id: 'bijie', nameZh: '毕节', nameEn: 'bijie', province: '贵州', latitude: 27.31, longitude: 105.29, priority: 72 },
  { id: 'liupanshui', nameZh: '六盘水', nameEn: 'liupanshui', province: '贵州', latitude: 26.6, longitude: 104.83, priority: 70 },
  { id: 'baoji', nameZh: '宝鸡', nameEn: 'baoji', province: '陕西', latitude: 34.36, longitude: 107.23, priority: 75 },
  { id: 'yulin', nameZh: '榆林', nameEn: 'yulin', province: '陕西', latitude: 38.3, longitude: 109.74, priority: 75 },
  { id: 'tianshui', nameZh: '天水', nameEn: 'tianshui', province: '甘肃', latitude: 34.58, longitude: 105.74, priority: 75 },
  { id: 'wuwei', nameZh: '武威', nameEn: 'wuwei', province: '甘肃', latitude: 37.93, longitude: 102.62, priority: 70 },
  { id: 'wuzhong', nameZh: '吴忠', nameEn: 'wuzhong', province: '宁夏', latitude: 37.99, longitude: 106.2, priority: 72 },
  { id: 'shizuishan', nameZh: '石嘴山', nameEn: 'shizuishan', province: '宁夏', latitude: 39.03, longitude: 106.38, priority: 70 },
  { id: 'turpan', nameZh: '吐鲁番', nameEn: 'turpan', province: '新疆', latitude: 42.95, longitude: 89.19, priority: 72 },
  { id: 'hami', nameZh: '哈密', nameEn: 'hami', province: '新疆', latitude: 42.82, longitude: 93.45, priority: 72 },
  { id: 'changdu', nameZh: '昌都', nameEn: 'changdu', province: '西藏', latitude: 31.14, longitude: 97.17, priority: 75 },
  { id: 'naqu', nameZh: '那曲', nameEn: 'naqu', province: '西藏', latitude: 31.48, longitude: 92.07, priority: 72 },
  { id: 'danzhou', nameZh: '儋州', nameEn: 'danzhou', province: '海南', latitude: 19.52, longitude: 109.58, priority: 72 },
  { id: 'putian', nameZh: '莆田', nameEn: 'putian', province: '福建', latitude: 25.43, longitude: 119.01, priority: 75 },
  { id: 'longyan', nameZh: '龙岩', nameEn: 'longyan', province: '福建', latitude: 25.08, longitude: 117.02, priority: 70 },
  { id: 'lianyungang', nameZh: '连云港', nameEn: 'lianyungang', province: '江苏', latitude: 34.56, longitude: 119.17, priority: 72 },
  { id: 'huaian', nameZh: '淮安', nameEn: 'huaian', province: '江苏', latitude: 33.58, longitude: 119.03, priority: 70 },
  { id: 'maoming', nameZh: '茂名', nameEn: 'maoming', province: '广东', latitude: 21.67, longitude: 110.93, priority: 70 },
  { id: 'zhaoqing', nameZh: '肇庆', nameEn: 'zhaoqing', province: '广东', latitude: 23.04, longitude: 112.44, priority: 72 },
  { id: 'dehong', nameZh: '德宏', nameEn: 'dehong', province: '云南', latitude: 24.44, longitude: 98.58, priority: 70 }
];

export function listChinaWeatherLocations(province?: string): ChinaWeatherLocation[] {
  const normalizedProvince = province?.trim();
  const locations = normalizedProvince
    ? CHINA_WEATHER_LOCATIONS.filter((location) => location.province.includes(normalizedProvince))
    : CHINA_WEATHER_LOCATIONS;

  return [...locations].sort((a, b) => b.priority - a.priority || a.nameZh.localeCompare(b.nameZh, 'zh-CN'));
}
